version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: SoftwarePersonalizationTechnologies/Dockerfile
    ports:
    - 4016:443 
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Passw0rd_1
    volumes:
    - mssqldata:/var/opt/mssql/data

volumes:
 mssqldata: